version: "2"

services:
  db:
    image: postgres
    volumes:
      - dbdata:/data/postgres
  api:
    build: .
    command: node index.js
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres

volumes:
  dbdata: